name: testing-python code

on:
  pull_request:
    branches:
      - main


jobs:
  Testing_python_code:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mle-dev
          environment-file: deploy/conda/env.yml
          auto-activate-base: false

      - name: Install Tree Cli
        run: |
          sudo apt install tree

      - name: Tree before build
        run: |
          tree

      - name: Build Package
        run: |
          pip install --upgrade setuptools
          pip install --upgrade build
          pip install -U pytest
          python -m build

      - name: Tree after build
        run: |
          tree
      - name: Install Package
        run: |
          pip install dist/*.whl
      - name: Test using Pytest
        run: |
          pytest tests/functional_tests/test_installation.py